//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTbl
    {
        public int OrderId { get; set; }
        public string CustomerCode { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> C_sum_TotalPrice___as_TotalOrder { get; set; }
        
    }
}
